/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_waem_ndklib_NativeWrapper */

#ifndef _Included_com_waem_ndklib_NativeWrapper
#define _Included_com_waem_ndklib_NativeWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_waem_ndklib_NativeWrapper
 * Method:    nativeSum
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_waem_ndklib_NativeWrapper_nativeSum
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
